### ISSUE TITLE
No repository link on crates.io

### ISSUE THREAD

**Issue by xubaiwang** [Pilfer/hermes_rs#1]
Please add `repository` or `homepage` fields to `Cargo.toml`. 
Otherwise repository information will be absent from crates.io, and users will fail to find this repo.

<table>
<tr>
<td>

![20241001_09h50m09s_grim](https://github.com/user-attachments/assets/3354db76-6777-4ecc-8f04-6f66a7f0becb)

</td>
<td>

![20241001_09h49m39s_grim](https://github.com/user-attachments/assets/7d454103-00bb-407d-a31b-eca8222e1135)

</td>
</tr>
</table>

Neither crates.io nor docs.rs contain link to this repository.

**Comment by Pilfer** [comment]
Resolved! Thank you for letting me know. :)
