### ISSUE TITLE
attempt to subtract with overflow

### ISSUE THREAD

**Issue by nikandlv** [Pilfer/hermes_rs#3]
Hi, thanks for the tool.

Im getting the following error with hbc v96

thread 'main' panicked at /.cargo/git/checkouts/hermes_rs-83b0ac72abb5c2b8/2c98032/src/hermes/debug_info.rs:59:35:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

let me know if you need the source bundle file.

Thanks

**Comment by Pilfer** [comment]
@nikandlv Hey there! Thanks for the report - I found a couple of bugs with the `debug_info` and function header parsing logic that I'm in the process of fixing. Try checking out the `dev` branch and see if that fixes the issue. I should have LargeFunctionHeader logic for both the disassembler and assembler portion fixed tomorrow.

**Comment by Pilfer** [comment]
@nikandlv Go ahead and re-pull from `main` and let me know if that resolved the issue. If not, I'll take a look when you've supplied your target bundle. 

Thanks again for reporting the issue :)

**Comment by nikandlv** [comment]
@Pilfer Amazing! Works perfectly 👌 
Sorry for the delay, i was busy at work 🥲
