### ISSUE TITLE
Panic when trying to dump bytecode/strings

### ISSUE THREAD

**Issue by aaravrav** [Pilfer/hermes_rs#9]
```rust
$ RUST_BACKTRACE=full cargo run --bin strings ../index.android.bundle
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/strings ../index.android.bundle`
thread 'main' panicked at /src/hermes/hermes_file/reader.rs:513:47:
Invalid UTF-16: FromUtf16Error(())
stack backtrace:
   0:     0x6387e1095402 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfa18e0fb89b78135
   1:     0x6387e10b1273 - core::fmt::write::h720837234efe462a
   2:     0x6387e109316f - std::io::Write::write_fmt::hd216aacc6845c401
   3:     0x6387e10952b2 - std::sys::backtrace::BacktraceLock::print::h31c66b38f3579e90
   4:     0x6387e1096204 - std::panicking::default_hook::{{closure}}::hadacae615ce1ff60
   5:     0x6387e1096046 - std::panicking::default_hook::hde7ba89eba787ec1
   6:     0x6387e1096812 - std::panicking::rust_panic_with_hook::h3ca700fbfdc8bc09
   7:     0x6387e109669a - std::panicking::begin_panic_handler::{{closure}}::hc4913e34838e09da
   8:     0x6387e10958c9 - std::sys::backtrace::__rust_end_short_backtrace::hcf902e9d29d24ab0
   9:     0x6387e10962fc - rust_begin_unwind
  10:     0x6387e1060190 - core::panicking::panic_fmt::h68842d4a61e10377
  11:     0x6387e1060506 - core::result::unwrap_failed::h0070dee92f992bb1
  12:     0x6387e1068ee6 - core::result::Result<T,E>::expect::hef2c9a6e0ec439cf
                               at /usr/src/debug/rust/rustc-1.83.0-src/library/core/src/result.rs:1061:23
  13:     0x6387e10647d9 - hermes_rs::hermes::hermes_file::reader::<impl hermes_rs::hermes::hermes_file::HermesFile<R>>::get_string_from_storage_by_index::hd0bdc47152dbeb44
                               at /src/hermes/hermes_file/reader.rs:513:13
  14:     0x6387e1061a6a - hermes_rs::hermes::hermes_file::reader::<impl hermes_rs::hermes::hermes_file::HermesFile<R>>::get_strings_by_kind::h218a873a048ea1dd
                               at src/hermes/hermes_file/reader.rs:463:37
  15:     0x6387e106bc3b - strings::main::h5bad4edd0aaf5f28
                               at /src/bin/strings.rs:26:23
  16:     0x6387e106fb9b - core::ops::function::FnOnce::call_once::h603f2c8e8d7cf97a
                               at /usr/src/debug/rust/rustc-1.83.0-src/library/core/src/ops/function.rs:250:5
  17:     0x6387e1068a9e - std::sys::backtrace::__rust_begin_short_backtrace::h2e58b02fb674f0ab
                               at /usr/src/debug/rust/rustc-1.83.0-src/library/std/src/sys/backtrace.rs:154:18
  18:     0x6387e106c661 - std::rt::lang_start::{{closure}}::h192cdb1e7b9b6170
                               at /usr/src/debug/rust/rustc-1.83.0-src/library/std/src/rt.rs:195:18
  19:     0x6387e1090bfe - std::rt::lang_start_internal::hae4dfaa265720ccd
  20:     0x6387e106c63a - std::rt::lang_start::hd283a8decafb7c08
                               at /usr/src/debug/rust/rustc-1.83.0-src/library/std/src/rt.rs:194:17
  21:     0x6387e106bf3e - main
  22:     0x74741112ae08 - <unknown>
  23:     0x74741112aecc - __libc_start_main
  24:     0x6387e1060985 - _start
  25:                0x0 - <unknown>
```

**Comment by Pilfer** [comment]
Hey, sorry - just seeing this. Can you provide the index.android.bundle you're having issues with? It looks like it's having a hard time parsing one or more UTF-16 strings.

**Comment by aaravrav** [comment]
> Hey, sorry - just seeing this. Can you provide the index.android.bundle you're having issues with? It looks like it's having a hard time parsing one or more UTF-16 strings.

Sure, I'll attach it: https://send.vis.ee/download/36071c3361139984/#4K1zbtRJKrvcLjtgLiFSWw

**Comment by Pilfer** [comment]
Looks like this is due to some invalid UTF16 characters that the original compiler added. It ended up failing around some i18n code, so maybe rust's String crate isn't great at handling that? 

Either way, I changed the utf16 func to a lossy one and was able to disassemble your bundle without issue.

Code changes: https://github.com/Pilfer/hermes_rs/commit/c5b13586b20acc454e8b1187025568f03c64293a

Let me know if you run into any other issues! Thanks :)

**Comment by aaravrav** [comment]
Awesome! Thanks alot for this repo. I think this is a mutual issue with hermes parsers, as I ran into the same issue with hasmer and hbctool (fork supporting v96), whilst hermes-dec did not fail, but produced wrong results.

**Comment by aaravrav** [comment]
P.S Is this project able to assemble the bytecode that it disassembled back into the bundle?

**Comment by Pilfer** [comment]
It should be able to, yes, however the assembler is the least tested portion of the project. You probably will run into issues with it, especially for larger bundles like this one that likely make use of RegExp etc. 

If you're trying to pull data out at runtime, check out my other project if you haven't already: https://github.com/Pilfer/heresy

**Comment by aaravrav** [comment]
> It should be able to, yes, however the assembler is the least tested portion of the project. You probably will run into issues with it, especially for larger bundles like this one that likely make use of RegExp etc.


@Pilfer Could you direct me to the relevant documentation at hand for that? I am not sure how to assemble exactly what hermes_rs disassembled, even if it might be experimental. Thanks.

**Comment by Pilfer** [comment]
@aaravrav There's not much documentation available beyond reading the code :(

- https://github.com/Pilfer/hermes_rs/blob/main/examples/create.rs
- https://github.com/facebook/hermes/
